version: "3.9"
services:
  node_express_monitoring_web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on: 
      - "persons-db"
    ports:
      - "3008:3000"
    volumes:
      -  ./:/usr/src/app
    environment:
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - PORT=${PORT}
      - POSTGRESQL_CONNSTRING=${POSTGRESQL_CONNSTRING}
  persons-db: 
     image: postgres
     environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test